type Query {
  hello: String

  order(id: ID!): Order

  orders: [Order]

  products: [Product]

  ordersByCustomer(name: String!): [Order]

  ordersByDateRange(start: String!, end: String!): [Order]

  topCustomers(limit: Int!): [CustomerOrderSummary]

  # ordersPagedSorted(offset: Int!, limit: Int!, direction: String!): [Order]
}

type Mutation {
  # Create
  createProduct(input: ProductInput!): Product

  # Update
  updateProduct(input: ProductInput!): Product

  # Delete
  deleteProduct(id: ID!): Boolean

  # Create Order
  createOrder(input: OrderInput!): Order
}

type Order {
  id: ID!
  customerName: String
  email: String
  createdDate: String
  lineItems: [LineItem]
}

type LineItem {
  id: ID!
  qty: Int
  product: Product
}

type Product {
  id: ID!
  name: String
}

type CustomerOrderSummary {
  customerName: String
  totalOrders: Int
}

enum OrderSortField {
  id
  customerName,
  email,
  createdAt
}

type OrderPage {
  content: [Order]
  page: Int
  size: Int
  totalElements: Int
  totalPages: Int
}

input ProductInput {
  id: ID
  name: String!
}

input OrderInput {
  id: ID
  customerName: String!
  email: String!
  items: [LineItemInput!]!
}

input LineItemInput {
  id: ID
  productId: ID!
  qty: Int!
}