type Query {
  hello: String

  order(id: ID!): Order

  orders: [Order]

  products: [Product]

  ordersByCustomer(name: String!): [Order]

  ordersByDateRange(start: String!, end: String!): [Order]

  topCustomers(limit: Int!): [CustomerOrderSummary]
}

type Order {
  id: ID!
  customerName: String
  email: String
  createdDate: String
  lineItems: [LineItem]
}

type LineItem {
  id: ID!
  qty: Int
  product: Product
}

type Product {
  id: ID!
  name: String
}

type CustomerOrderSummary {
  customerName: String
  totalOrders: Int
}